// ===== A1 «İlk Adımlar» — 12 миссий =====
// Каждая миссия ссылается на существующий контент по id:
//   wordIds  → WORDS[].n      verbIds → VERBS[].id
//   grammarId → GRAMMAR_LESSONS[].id   phraseIds → PHRASES[].id
// dialog / game / test — самодостаточны (текст внутри миссии).

const MISSIONS = [
  {
    id: 1, level: 'A1', emoji: '🌹', title: 'Первое сообщение',
    goal: 'Он написал первым. Ответь так, чтобы захотелось продолжить разговор.',
    wordIds: [4, 5, 18, 48, 52, 49, 50, 46],
    verbIds: [16, 8], grammarId: 4, phraseIds: [21, 22, 23, 26],
    dialog: [
      { s: 'he', tr: 'Merhaba 🙂', ru: 'Привет' },
      { s: 'he', tr: 'Nasılsın?', ru: 'Как ты?' },
      { s: 'you', tr: 'İyiyim, teşekkürler! Sen nasılsın?', ru: 'Хорошо, спасибо! А ты как?' },
      { s: 'he', tr: 'Ben de iyiyim. Seni düşünüyorum 💭', ru: 'Я тоже хорошо. Думаю о тебе' },
      { s: 'choose', q: 'Что ответить?', options: [
        { tr: 'Ben de seni düşünüyorum 💕', ru: 'Я тоже о тебе думаю', correct: true },
        { tr: 'Hoşça kal', ru: 'Прощай', correct: false },
        { tr: 'Anlamıyorum', ru: 'Не понимаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Seni düşünüyorum', ru: 'Думаю о тебе' },
    test: [
      { q: 'Merhaba', a: 'Привет', opts: ['Привет', 'Пока', 'Спасибо', 'Извини'] },
      { q: 'Nasılsın?', a: 'Как ты?', opts: ['Как ты?', 'Где ты?', 'Кто ты?', 'Когда?'] },
      { q: 'Seni düşünüyorum', a: 'Думаю о тебе', opts: ['Думаю о тебе', 'Скучаю по тебе', 'Люблю тебя', 'Жду тебя'] },
      { q: 'Как сказать «я тоже хорошо»?', a: 'Ben de iyiyim', opts: ['Ben de iyiyim', 'Nasılsın', 'Hoşça kal', 'Teşekkürler'] },
      { q: 'Aşkım', a: 'Любовь моя', opts: ['Любовь моя', 'Друг мой', 'Брат', 'Сосед'] },
    ],
    reward: { xp: 50, badge: '🌹', readiness: 2 },
  },
  {
    id: 2, level: 'A1', emoji: '👋', title: 'Знакомство',
    goal: 'Вы встретились вживую. Представься и узнай о нём.',
    wordIds: [46, 32, 33, 25, 26, 68],
    verbIds: [17, 13], grammarId: 3, phraseIds: [1, 2, 3, 9],
    dialog: [
      { s: 'he', tr: 'Memnun oldum! Adın ne?', ru: 'Приятно познакомиться! Как тебя зовут?' },
      { s: 'you', tr: 'Benim adım Ksenia. Senin adın ne?', ru: 'Меня зовут Ксения. А тебя?' },
      { s: 'he', tr: 'Ben Mehmet. Nerelisin?', ru: 'Я Мехмет. Откуда ты?' },
      { s: 'choose', q: 'Как ответить «Я из России»?', options: [
        { tr: 'Rusyalıyım', ru: 'Я из России', correct: true },
        { tr: 'Türkçe öğreniyorum', ru: 'Я учу турецкий', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Benim adım Ksenia', ru: 'Меня зовут Ксения' },
    test: [
      { q: 'Adın ne?', a: 'Как тебя зовут?', opts: ['Как тебя зовут?', 'Сколько тебе лет?', 'Где ты?', 'Что делаешь?'] },
      { q: 'Memnun oldum', a: 'Приятно познакомиться', opts: ['Приятно познакомиться', 'Доброе утро', 'Спокойной ночи', 'Как дела?'] },
      { q: 'Nerelisin?', a: 'Откуда ты?', opts: ['Откуда ты?', 'Кто ты?', 'Куда идёшь?', 'Зачем?'] },
      { q: 'Tanışmak', a: 'Познакомиться', opts: ['Познакомиться', 'Встречаться', 'Расставаться', 'Звонить'] },
      { q: 'Как сказать «Меня зовут...»?', a: 'Benim adım...', opts: ['Benim adım...', 'Nasılsın', 'Nerelisin', 'Memnun oldum'] },
    ],
    reward: { xp: 50, badge: '👋', readiness: 2 },
  },
  {
    id: 3, level: 'A1', emoji: '☕', title: 'Первое свидание',
    goal: 'Спланируй свидание и пригласи его в кафе.',
    wordIds: [32, 33, 45, 384, 407, 408],
    verbIds: [2, 12], grammarId: 4, phraseIds: [11, 16, 17, 18],
    dialog: [
      { s: 'he', tr: 'Bu akşam müsait misin?', ru: 'Ты свободна сегодня вечером?' },
      { s: 'you', tr: 'Evet, müsaitim 🙂', ru: 'Да, свободна' },
      { s: 'he', tr: 'Bir kahve içelim mi?', ru: 'Выпьем кофе?' },
      { s: 'choose', q: 'Согласись красиво', options: [
        { tr: 'Harika olur, çok isterim!', ru: 'Было бы здорово, очень хочу!', correct: true },
        { tr: 'Hayır, istemiyorum', ru: 'Нет, не хочу', correct: false },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bir kahve içelim mi', ru: 'Выпьем кофе?' },
    test: [
      { q: 'Bir kahve içelim mi?', a: 'Выпьем кофе?', opts: ['Выпьем кофе?', 'Поедим?', 'Пойдём домой?', 'Который час?'] },
      { q: 'Buluşma', a: 'Свидание', opts: ['Свидание', 'Работа', 'Магазин', 'Дорога'] },
      { q: 'Müsait misin?', a: 'Ты свободна?', opts: ['Ты свободна?', 'Ты устала?', 'Ты голодна?', 'Ты дома?'] },
      { q: 'içmek', a: 'пить', opts: ['пить', 'есть', 'идти', 'спать'] },
      { q: 'Как предложить встречу вечером?', a: 'Bu akşam buluşalım mı?', opts: ['Bu akşam buluşalım mı?', 'Nasılsın?', 'Hoşça kal', 'Anladım'] },
    ],
    reward: { xp: 60, badge: '☕', readiness: 3 },
  },
  {
    id: 4, level: 'A1', emoji: '💬', title: 'Каждый день на связи',
    goal: 'Утреннее и вечернее сообщение — турки это обожают.',
    wordIds: [52, 18, 54, 490, 491, 21],
    verbIds: [16, 15], grammarId: 4, phraseIds: [21, 26, 27, 29],
    dialog: [
      { s: 'he', tr: 'Günaydın güzelim ☀️', ru: 'Доброе утро, красавица' },
      { s: 'you', tr: 'Günaydın! İyi uyudun mu?', ru: 'Доброе утро! Хорошо спал?' },
      { s: 'he', tr: 'Evet, seni rüyamda gördüm 😍', ru: 'Да, видел тебя во сне' },
      { s: 'choose', q: 'Ответь нежно', options: [
        { tr: 'Çok tatlısın 🥰', ru: 'Ты такой милый', correct: true },
        { tr: 'Önemli değil', ru: 'Не важно', correct: false },
        { tr: 'Geç kaldım', ru: 'Я опоздала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'İyi geceler canım', ru: 'Спокойной ночи, дорогой' },
    test: [
      { q: 'Günaydın', a: 'Доброе утро', opts: ['Доброе утро', 'Добрый вечер', 'Спокойной ночи', 'Добрый день'] },
      { q: 'İyi geceler', a: 'Спокойной ночи', opts: ['Спокойной ночи', 'Доброе утро', 'Привет', 'Пока'] },
      { q: 'Seni özledim', a: 'Я скучала по тебе', opts: ['Я скучала по тебе', 'Я люблю тебя', 'Я думаю о тебе', 'Я жду тебя'] },
      { q: 'Her zaman', a: 'Всегда', opts: ['Всегда', 'Никогда', 'Иногда', 'Сейчас'] },
      { q: 'Как сказать «сладких снов»?', a: 'Tatlı rüyalar', opts: ['Tatlı rüyalar', 'Günaydın', 'Nasılsın', 'Teşekkürler'] },
    ],
    reward: { xp: 50, badge: '💬', readiness: 2 },
  },
  {
    id: 5, level: 'A1', emoji: '😊', title: 'Комплименты',
    goal: 'Научись делать и принимать комплименты по-турецки.',
    wordIds: [43, 44, 9, 96, 98, 99],
    verbIds: [6, 14], grammarId: 3, phraseIds: [6, 9, 11, 13],
    dialog: [
      { s: 'he', tr: 'Bugün çok güzelsin 😍', ru: 'Сегодня ты очень красивая' },
      { s: 'you', tr: 'Teşekkür ederim! Sen de çok yakışıklısın', ru: 'Спасибо! Ты тоже очень красивый' },
      { s: 'he', tr: 'Gözlerin harika', ru: 'У тебя потрясающие глаза' },
      { s: 'choose', q: 'Прими комплимент', options: [
        { tr: 'Çok naziksin 💕', ru: 'Ты очень милый', correct: true },
        { tr: 'Yalan söylüyorsun', ru: 'Ты врёшь', correct: false },
        { tr: 'Hayır', ru: 'Нет', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Çok güzelsin', ru: 'Ты очень красивая' },
    test: [
      { q: 'Çok güzelsin', a: 'Ты очень красивая', opts: ['Ты очень красивая', 'Ты очень умная', 'Ты очень добрая', 'Ты очень весёлая'] },
      { q: 'Yakışıklı', a: 'Красивый (о мужчине)', opts: ['Красивый (о мужчине)', 'Высокий', 'Сильный', 'Богатый'] },
      { q: 'Gözlerin', a: 'Твои глаза', opts: ['Твои глаза', 'Твои волосы', 'Твой голос', 'Твои руки'] },
      { q: 'Teşekkür ederim', a: 'Спасибо', opts: ['Спасибо', 'Пожалуйста', 'Извини', 'Не за что'] },
      { q: 'Как сказать «ты тоже красивый»?', a: 'Sen de yakışıklısın', opts: ['Sen de yakışıklısın', 'Çok güzelsin', 'Nasılsın', 'Görüşürüz'] },
    ],
    reward: { xp: 50, badge: '😊', readiness: 2 },
  },
  {
    id: 6, level: 'A1', emoji: '📞', title: 'Голосовые и звонки',
    goal: 'Турки обожают голосовые. Научись назначать звонок.',
    wordIds: [49, 50, 51, 48, 98, 84],
    verbIds: [13, 2], grammarId: 4, phraseIds: [24, 25, 28],
    dialog: [
      { s: 'he', tr: 'Sesini özledim, arayabilir miyim?', ru: 'Скучаю по твоему голосу, можно позвонить?' },
      { s: 'you', tr: 'Tabii ki! Beni ara 📞', ru: 'Конечно! Позвони мне' },
      { s: 'he', tr: 'Görüntülü mü sesli mi?', ru: 'Видео или аудио?' },
      { s: 'choose', q: 'Выбери видеозвонок', options: [
        { tr: 'Görüntülü arayalım 📹', ru: 'Давай по видео', correct: true },
        { tr: 'Hiç arama', ru: 'Не звони вообще', correct: false },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Beni ara lütfen', ru: 'Позвони мне, пожалуйста' },
    test: [
      { q: 'Aramak', a: 'Звонить', opts: ['Звонить', 'Писать', 'Ждать', 'Идти'] },
      { q: 'Sesli mesaj', a: 'Голосовое сообщение', opts: ['Голосовое сообщение', 'Видеозвонок', 'Фото', 'Письмо'] },
      { q: 'Görüntülü aramak', a: 'Видеозвонок', opts: ['Видеозвонок', 'Голосовое', 'Смс', 'Чат'] },
      { q: 'Sesini özledim', a: 'Скучаю по твоему голосу', opts: ['Скучаю по твоему голосу', 'Люблю твой голос', 'Слышу тебя', 'Звоню тебе'] },
      { q: 'Как сказать «позвони мне»?', a: 'Beni ara', opts: ['Beni ara', 'Bana yaz', 'Gel buraya', 'Bekle'] },
    ],
    reward: { xp: 50, badge: '📞', readiness: 2 },
  },
  {
    id: 7, level: 'A1', emoji: '🍽️', title: 'В кафе вместе',
    goal: 'Закажи еду и напитки на вашем свидании в кафе.',
    wordIds: [384, 385, 386, 407, 408, 326],
    verbIds: [11, 12], grammarId: 4, phraseIds: [12, 13],
    dialog: [
      { s: 'he', tr: 'Ne içmek istersin?', ru: 'Что будешь пить?' },
      { s: 'you', tr: 'Bir Türk kahvesi lütfen', ru: 'Один турецкий кофе, пожалуйста' },
      { s: 'he', tr: 'Yemek de ister misin?', ru: 'Хочешь и поесть?' },
      { s: 'choose', q: 'Закажи десерт', options: [
        { tr: 'Bir tatlı alalım 🍰', ru: 'Возьмём десерт', correct: true },
        { tr: 'Hesap lütfen', ru: 'Счёт, пожалуйста', correct: false },
        { tr: 'Gitmek istiyorum', ru: 'Хочу уйти', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bir Türk kahvesi lütfen', ru: 'Один турецкий кофе, пожалуйста' },
    test: [
      { q: 'Ne içmek istersin?', a: 'Что будешь пить?', opts: ['Что будешь пить?', 'Что будешь есть?', 'Куда пойдём?', 'Который час?'] },
      { q: 'Hesap lütfen', a: 'Счёт, пожалуйста', opts: ['Счёт, пожалуйста', 'Меню, пожалуйста', 'Воды, пожалуйста', 'Помогите'] },
      { q: 'Restoran', a: 'Ресторан', opts: ['Ресторан', 'Магазин', 'Банк', 'Аптека'] },
      { q: 'yemek', a: 'есть / еда', opts: ['есть / еда', 'пить', 'спать', 'идти'] },
      { q: 'Türk kahvesi', a: 'Турецкий кофе', opts: ['Турецкий кофе', 'Чай', 'Сок', 'Вода'] },
    ],
    reward: { xp: 60, badge: '🍽️', readiness: 3 },
  },
  {
    id: 8, level: 'A1', emoji: '🛍️', title: 'Вместе по магазинам',
    goal: 'Спроси цену, попроси скидку, расплатись.',
    wordIds: [342, 344, 345, 346, 347, 349],
    verbIds: [9, 14], grammarId: 5, phraseIds: [53],
    dialog: [
      { s: 'you', tr: 'Bu ne kadar?', ru: 'Сколько это стоит?' },
      { s: 'he', tr: 'Yüz lira', ru: 'Сто лир' },
      { s: 'you', tr: 'Biraz pahalı, indirim var mı?', ru: 'Дороговато, есть скидка?' },
      { s: 'choose', q: 'Расплатись картой', options: [
        { tr: 'Kartla ödeyebilir miyim?', ru: 'Можно картой?', correct: true },
        { tr: 'Çok güzel', ru: 'Очень красиво', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bu ne kadar', ru: 'Сколько это стоит?' },
    test: [
      { q: 'Bu ne kadar?', a: 'Сколько это стоит?', opts: ['Сколько это стоит?', 'Что это?', 'Где это?', 'Чьё это?'] },
      { q: 'Pahalı', a: 'Дорогой', opts: ['Дорогой', 'Дешёвый', 'Красивый', 'Большой'] },
      { q: 'İndirim', a: 'Скидка', opts: ['Скидка', 'Цена', 'Деньги', 'Карта'] },
      { q: 'Ucuz', a: 'Дешёвый', opts: ['Дешёвый', 'Дорогой', 'Новый', 'Старый'] },
      { q: 'Как спросить про скидку?', a: 'İndirim var mı?', opts: ['İndirim var mı?', 'Ne kadar?', 'Nerede?', 'Kim?'] },
    ],
    reward: { xp: 50, badge: '🛍️', readiness: 2 },
  },
  {
    id: 9, level: 'A1', emoji: '🚕', title: 'Такси и транспорт',
    goal: 'Объясни водителю, куда ехать, и доберись сама.',
    wordIds: [372, 373, 374, 375, 376],
    verbIds: [3, 2], grammarId: 5, phraseIds: [],
    dialog: [
      { s: 'you', tr: 'Taksim\'e gitmek istiyorum', ru: 'Хочу поехать в Таксим' },
      { s: 'he', tr: 'Tabii, buyurun', ru: 'Конечно, садитесь' },
      { s: 'you', tr: 'Ne kadar sürer?', ru: 'Сколько займёт?' },
      { s: 'choose', q: 'Попроси остановить здесь', options: [
        { tr: 'Burada durabilir misiniz?', ru: 'Можете остановить здесь?', correct: true },
        { tr: 'Çok hızlı', ru: 'Очень быстро', correct: false },
        { tr: 'Teşekkürler', ru: 'Спасибо', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Taksime gitmek istiyorum', ru: 'Хочу поехать в Таксим' },
    test: [
      { q: 'Taksi', a: 'Такси', opts: ['Такси', 'Автобус', 'Метро', 'Поезд'] },
      { q: 'gitmek', a: 'идти / ехать', opts: ['идти / ехать', 'приходить', 'ждать', 'стоять'] },
      { q: 'Otobüs', a: 'Автобус', opts: ['Автобус', 'Такси', 'Машина', 'Метро'] },
      { q: 'Ne kadar sürer?', a: 'Сколько займёт?', opts: ['Сколько займёт?', 'Сколько стоит?', 'Где это?', 'Куда едем?'] },
      { q: 'Как сказать «остановите здесь»?', a: 'Burada durun', opts: ['Burada durun', 'Hızlı gidin', 'Sağa dönün', 'Bekleyin'] },
    ],
    reward: { xp: 50, badge: '🚕', readiness: 2 },
  },
  {
    id: 10, level: 'A1', emoji: '❤️', title: 'Признание в чувствах',
    goal: 'Самый важный момент — скажи о своих чувствах.',
    wordIds: [19, 20, 1, 60, 21, 87],
    verbIds: [6, 5], grammarId: 4, phraseIds: [7, 10, 19],
    dialog: [
      { s: 'he', tr: 'Sana bir şey söylemek istiyorum...', ru: 'Хочу тебе кое-что сказать...' },
      { s: 'he', tr: 'Seni seviyorum ❤️', ru: 'Я тебя люблю' },
      { s: 'choose', q: 'Признайся в ответ', options: [
        { tr: 'Ben de seni seviyorum 💕', ru: 'Я тоже тебя люблю', correct: true },
        { tr: 'Teşekkürler', ru: 'Спасибо', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
      { s: 'he', tr: 'Sen benim hayatımsın', ru: 'Ты моя жизнь' },
    ],
    game: { type: 'build', tr: 'Ben de seni seviyorum', ru: 'Я тоже тебя люблю' },
    test: [
      { q: 'Seni seviyorum', a: 'Я тебя люблю', opts: ['Я тебя люблю', 'Я по тебе скучаю', 'Я думаю о тебе', 'Я тебя жду'] },
      { q: 'Aşk', a: 'Любовь', opts: ['Любовь', 'Дружба', 'Жизнь', 'Сердце'] },
      { q: 'Sana aşığım', a: 'Я влюблён в тебя', opts: ['Я влюблён в тебя', 'Я скучаю', 'Я рад', 'Я устал'] },
      { q: 'Gerçek aşk', a: 'Настоящая любовь', opts: ['Настоящая любовь', 'Первая любовь', 'Старая любовь', 'Тайная любовь'] },
      { q: 'Как ответить «я тоже тебя люблю»?', a: 'Ben de seni seviyorum', opts: ['Ben de seni seviyorum', 'Seni özledim', 'İyi geceler', 'Teşekkürler'] },
    ],
    reward: { xp: 70, badge: '❤️', readiness: 4 },
  },
  {
    id: 11, level: 'A1', emoji: '🗓️', title: 'Планы на выходные',
    goal: 'Договоритесь, как провести выходные вместе.',
    wordIds: [383, 387, 390, 419, 54],
    verbIds: [4, 1], grammarId: 4, phraseIds: [56, 59],
    dialog: [
      { s: 'he', tr: 'Hafta sonu ne yapalım?', ru: 'Что будем делать на выходных?' },
      { s: 'you', tr: 'Bir film izleyelim mi?', ru: 'Посмотрим фильм?' },
      { s: 'he', tr: 'Olur! Veya gezeriz', ru: 'Давай! Или погуляем' },
      { s: 'choose', q: 'Предложи прогулку', options: [
        { tr: 'Deniz kenarına gidelim 🌊', ru: 'Поедем к морю', correct: true },
        { tr: 'Çalışmam lazım', ru: 'Мне надо работать', correct: false },
        { tr: 'Yorgunum', ru: 'Я устала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Hafta sonu ne yapalım', ru: 'Что будем делать на выходных?' },
    test: [
      { q: 'Hafta sonu', a: 'Выходные', opts: ['Выходные', 'Понедельник', 'Утро', 'Вечер'] },
      { q: 'Gezmek', a: 'Гулять', opts: ['Гулять', 'Работать', 'Спать', 'Готовить'] },
      { q: 'Sinema', a: 'Кино', opts: ['Кино', 'Театр', 'Музей', 'Парк'] },
      { q: 'yapmak', a: 'делать', opts: ['делать', 'идти', 'видеть', 'хотеть'] },
      { q: 'Как предложить «посмотрим фильм»?', a: 'Film izleyelim mi?', opts: ['Film izleyelim mi?', 'Ne yapalım?', 'Nereye gidelim?', 'Yorgun musun?'] },
    ],
    reward: { xp: 50, badge: '🗓️', readiness: 2 },
  },
  {
    id: 12, level: 'A1', emoji: '🎁', title: 'Праздники и подарки',
    goal: 'Поздравь его и выбери подарок к особому дню.',
    wordIds: [212, 195, 215, 214, 73],
    verbIds: [9, 10], grammarId: 5, phraseIds: [36, 46],
    dialog: [
      { s: 'he', tr: 'Bugün doğum günüm 🎂', ru: 'Сегодня мой день рождения' },
      { s: 'choose', q: 'Поздравь его', options: [
        { tr: 'İyi ki doğdun! 🎉', ru: 'С днём рождения!', correct: true },
        { tr: 'Geçmiş olsun', ru: 'Выздоравливай', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
      { s: 'he', tr: 'Çok teşekkür ederim canım 🥰', ru: 'Большое спасибо, дорогая' },
      { s: 'you', tr: 'Sana bir hediye aldım', ru: 'Я купила тебе подарок' },
    ],
    game: { type: 'build', tr: 'İyi ki doğdun', ru: 'С днём рождения' },
    test: [
      { q: 'Doğum günü', a: 'День рождения', opts: ['День рождения', 'Новый год', 'Свадьба', 'Праздник'] },
      { q: 'İyi ki doğdun', a: 'С днём рождения', opts: ['С днём рождения', 'С Новым годом', 'Поздравляю', 'Выздоравливай'] },
      { q: 'Hediye', a: 'Подарок', opts: ['Подарок', 'Цветы', 'Торт', 'Открытка'] },
      { q: 'Bayram', a: 'Праздник', opts: ['Праздник', 'Будни', 'Выходной', 'Отпуск'] },
      { q: 'Как сказать «я купила подарок»?', a: 'Hediye aldım', opts: ['Hediye aldım', 'Hediye verdim', 'Çiçek aldım', 'Teşekkürler'] },
    ],
    reward: { xp: 60, badge: '🎁', readiness: 3 },
  },
];

const A1_EXAM = {
  level: 'A1',
  title: 'Экзамен A1 «İlk Adımlar»',
  pass: 70,
  questions: [
    { sec: 'Лексика', q: 'Aşkım', a: 'Любовь моя', opts: ['Любовь моя', 'Друг мой', 'Брат', 'Сосед'] },
    { sec: 'Лексика', q: 'Buluşma', a: 'Свидание', opts: ['Свидание', 'Работа', 'Магазин', 'Дорога'] },
    { sec: 'Лексика', q: 'İndirim', a: 'Скидка', opts: ['Скидка', 'Цена', 'Деньги', 'Чек'] },
    { sec: 'Грамматика', q: '«Я думаю» — это...', a: 'düşünüyorum', opts: ['düşünüyorum', 'düşünüyorsun', 'düşünüyor', 'düşündüm'] },
    { sec: 'Грамматика', q: 'Отрицание «не понимаю»', a: 'anlamıyorum', opts: ['anlamıyorum', 'anlıyorum', 'anladım', 'anlarım'] },
    { sec: 'Грамматика', q: 'Вопрос «выпьем кофе?»', a: 'Kahve içelim mi?', opts: ['Kahve içelim mi?', 'Kahve içiyorum', 'Kahve istemiyorum', 'Kahve güzel'] },
    { sec: 'Чтение', q: '«Bu akşam müsait misin?» означает...', a: 'Ты свободна сегодня вечером?', opts: ['Ты свободна сегодня вечером?', 'Что ты делаешь?', 'Где ты живёшь?', 'Как тебя зовут?'] },
    { sec: 'Ситуация', q: 'Он написал «Seni seviyorum». Ответь:', a: 'Ben de seni seviyorum', opts: ['Ben de seni seviyorum', 'Görüşürüz', 'Teşekkürler', 'Anlamıyorum'] },
    { sec: 'Ситуация', q: 'В кафе хочешь кофе. Скажи:', a: 'Bir kahve lütfen', opts: ['Bir kahve lütfen', 'Hesap lütfen', 'Çok pahalı', 'Gitmek istiyorum'] },
    { sec: 'Ситуация', q: 'Поздравь с днём рождения:', a: 'İyi ki doğdun', opts: ['İyi ki doğdun', 'Geçmiş olsun', 'Güle güle', 'Afiyet olsun'] },
  ],
};
