// ===== A1 «İlk Adımlar» — 12 миссий =====
// Каждая миссия ссылается на существующий контент по id:
//   wordIds  → WORDS[].n      verbIds → VERBS[].id
//   grammarId → GRAMMAR_LESSONS[].id   phraseIds → PHRASES[].id
// dialog / game / test — самодостаточны (текст внутри миссии).

const MISSIONS = [
  {
    id: 1, level: 'A1', emoji: '🌹', title: 'Первое сообщение',
    goal: 'Он написал первым. Ответь так, чтобы захотелось продолжить разговор.',
    wordIds: [4, 5, 18, 48, 52, 49, 50, 46],
    verbIds: [16, 8], grammarId: 4, phraseIds: [21, 22, 23, 26],
    dialog: [
      { s: 'he', tr: 'Merhaba 🙂', ru: 'Привет' },
      { s: 'he', tr: 'Nasılsın?', ru: 'Как ты?' },
      { s: 'you', tr: 'İyiyim, teşekkürler! Sen nasılsın?', ru: 'Хорошо, спасибо! А ты как?' },
      { s: 'he', tr: 'Ben de iyiyim. Seni düşünüyorum 💭', ru: 'Я тоже хорошо. Думаю о тебе' },
      { s: 'choose', q: 'Что ответить?', options: [
        { tr: 'Ben de seni düşünüyorum 💕', ru: 'Я тоже о тебе думаю', correct: true },
        { tr: 'Hoşça kal', ru: 'Прощай', correct: false },
        { tr: 'Anlamıyorum', ru: 'Не понимаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Seni düşünüyorum', ru: 'Думаю о тебе' },
    test: [
      { q: 'Merhaba', a: 'Привет', opts: ['Привет', 'Пока', 'Спасибо', 'Извини'] },
      { q: 'Nasılsın?', a: 'Как ты?', opts: ['Как ты?', 'Где ты?', 'Кто ты?', 'Когда?'] },
      { q: 'Seni düşünüyorum', a: 'Думаю о тебе', opts: ['Думаю о тебе', 'Скучаю по тебе', 'Люблю тебя', 'Жду тебя'] },
      { q: 'Как сказать «я тоже хорошо»?', a: 'Ben de iyiyim', opts: ['Ben de iyiyim', 'Nasılsın', 'Hoşça kal', 'Teşekkürler'] },
      { q: 'Aşkım', a: 'Любовь моя', opts: ['Любовь моя', 'Друг мой', 'Брат', 'Сосед'] },
    ],
    reward: { xp: 50, badge: '🌹', readiness: 2 },
  },
  {
    id: 2, level: 'A1', emoji: '👋', title: 'Знакомство',
    goal: 'Вы встретились вживую. Представься и узнай о нём.',
    wordIds: [46, 32, 33, 25, 26, 68],
    verbIds: [17, 13], grammarId: 3, phraseIds: [1, 2, 3, 9],
    dialog: [
      { s: 'he', tr: 'Memnun oldum! Adın ne?', ru: 'Приятно познакомиться! Как тебя зовут?' },
      { s: 'you', tr: 'Benim adım Ksenia. Senin adın ne?', ru: 'Меня зовут Ксения. А тебя?' },
      { s: 'he', tr: 'Ben Mehmet. Nerelisin?', ru: 'Я Мехмет. Откуда ты?' },
      { s: 'choose', q: 'Как ответить «Я из России»?', options: [
        { tr: 'Rusyalıyım', ru: 'Я из России', correct: true },
        { tr: 'Türkçe öğreniyorum', ru: 'Я учу турецкий', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Benim adım Ksenia', ru: 'Меня зовут Ксения' },
    test: [
      { q: 'Adın ne?', a: 'Как тебя зовут?', opts: ['Как тебя зовут?', 'Сколько тебе лет?', 'Где ты?', 'Что делаешь?'] },
      { q: 'Memnun oldum', a: 'Приятно познакомиться', opts: ['Приятно познакомиться', 'Доброе утро', 'Спокойной ночи', 'Как дела?'] },
      { q: 'Nerelisin?', a: 'Откуда ты?', opts: ['Откуда ты?', 'Кто ты?', 'Куда идёшь?', 'Зачем?'] },
      { q: 'Tanışmak', a: 'Познакомиться', opts: ['Познакомиться', 'Встречаться', 'Расставаться', 'Звонить'] },
      { q: 'Как сказать «Меня зовут...»?', a: 'Benim adım...', opts: ['Benim adım...', 'Nasılsın', 'Nerelisin', 'Memnun oldum'] },
    ],
    reward: { xp: 50, badge: '👋', readiness: 2 },
  },
  {
    id: 3, level: 'A1', emoji: '☕', title: 'Первое свидание',
    goal: 'Спланируй свидание и пригласи его в кафе.',
    wordIds: [32, 33, 45, 384, 407, 408],
    verbIds: [2, 12], grammarId: 4, phraseIds: [11, 16, 17, 18],
    dialog: [
      { s: 'he', tr: 'Bu akşam müsait misin?', ru: 'Ты свободна сегодня вечером?' },
      { s: 'you', tr: 'Evet, müsaitim 🙂', ru: 'Да, свободна' },
      { s: 'he', tr: 'Bir kahve içelim mi?', ru: 'Выпьем кофе?' },
      { s: 'choose', q: 'Согласись красиво', options: [
        { tr: 'Harika olur, çok isterim!', ru: 'Было бы здорово, очень хочу!', correct: true },
        { tr: 'Hayır, istemiyorum', ru: 'Нет, не хочу', correct: false },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bir kahve içelim mi', ru: 'Выпьем кофе?' },
    test: [
      { q: 'Bir kahve içelim mi?', a: 'Выпьем кофе?', opts: ['Выпьем кофе?', 'Поедим?', 'Пойдём домой?', 'Который час?'] },
      { q: 'Buluşma', a: 'Свидание', opts: ['Свидание', 'Работа', 'Магазин', 'Дорога'] },
      { q: 'Müsait misin?', a: 'Ты свободна?', opts: ['Ты свободна?', 'Ты устала?', 'Ты голодна?', 'Ты дома?'] },
      { q: 'içmek', a: 'пить', opts: ['пить', 'есть', 'идти', 'спать'] },
      { q: 'Как предложить встречу вечером?', a: 'Bu akşam buluşalım mı?', opts: ['Bu akşam buluşalım mı?', 'Nasılsın?', 'Hoşça kal', 'Anladım'] },
    ],
    reward: { xp: 60, badge: '☕', readiness: 3 },
  },
  {
    id: 4, level: 'A1', emoji: '💬', title: 'Каждый день на связи',
    goal: 'Утреннее и вечернее сообщение — турки это обожают.',
    wordIds: [52, 18, 54, 490, 491, 21],
    verbIds: [16, 15], grammarId: 4, phraseIds: [21, 26, 27, 29],
    dialog: [
      { s: 'he', tr: 'Günaydın güzelim ☀️', ru: 'Доброе утро, красавица' },
      { s: 'you', tr: 'Günaydın! İyi uyudun mu?', ru: 'Доброе утро! Хорошо спал?' },
      { s: 'he', tr: 'Evet, seni rüyamda gördüm 😍', ru: 'Да, видел тебя во сне' },
      { s: 'choose', q: 'Ответь нежно', options: [
        { tr: 'Çok tatlısın 🥰', ru: 'Ты такой милый', correct: true },
        { tr: 'Önemli değil', ru: 'Не важно', correct: false },
        { tr: 'Geç kaldım', ru: 'Я опоздала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'İyi geceler canım', ru: 'Спокойной ночи, дорогой' },
    test: [
      { q: 'Günaydın', a: 'Доброе утро', opts: ['Доброе утро', 'Добрый вечер', 'Спокойной ночи', 'Добрый день'] },
      { q: 'İyi geceler', a: 'Спокойной ночи', opts: ['Спокойной ночи', 'Доброе утро', 'Привет', 'Пока'] },
      { q: 'Seni özledim', a: 'Я скучала по тебе', opts: ['Я скучала по тебе', 'Я люблю тебя', 'Я думаю о тебе', 'Я жду тебя'] },
      { q: 'Her zaman', a: 'Всегда', opts: ['Всегда', 'Никогда', 'Иногда', 'Сейчас'] },
      { q: 'Как сказать «сладких снов»?', a: 'Tatlı rüyalar', opts: ['Tatlı rüyalar', 'Günaydın', 'Nasılsın', 'Teşekkürler'] },
    ],
    reward: { xp: 50, badge: '💬', readiness: 2 },
  },
  {
    id: 5, level: 'A1', emoji: '😊', title: 'Комплименты',
    goal: 'Научись делать и принимать комплименты по-турецки.',
    wordIds: [43, 44, 9, 96, 98, 99],
    verbIds: [6, 14], grammarId: 3, phraseIds: [6, 9, 11, 13],
    dialog: [
      { s: 'he', tr: 'Bugün çok güzelsin 😍', ru: 'Сегодня ты очень красивая' },
      { s: 'you', tr: 'Teşekkür ederim! Sen de çok yakışıklısın', ru: 'Спасибо! Ты тоже очень красивый' },
      { s: 'he', tr: 'Gözlerin harika', ru: 'У тебя потрясающие глаза' },
      { s: 'choose', q: 'Прими комплимент', options: [
        { tr: 'Çok naziksin 💕', ru: 'Ты очень милый', correct: true },
        { tr: 'Yalan söylüyorsun', ru: 'Ты врёшь', correct: false },
        { tr: 'Hayır', ru: 'Нет', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Çok güzelsin', ru: 'Ты очень красивая' },
    test: [
      { q: 'Çok güzelsin', a: 'Ты очень красивая', opts: ['Ты очень красивая', 'Ты очень умная', 'Ты очень добрая', 'Ты очень весёлая'] },
      { q: 'Yakışıklı', a: 'Красивый (о мужчине)', opts: ['Красивый (о мужчине)', 'Высокий', 'Сильный', 'Богатый'] },
      { q: 'Gözlerin', a: 'Твои глаза', opts: ['Твои глаза', 'Твои волосы', 'Твой голос', 'Твои руки'] },
      { q: 'Teşekkür ederim', a: 'Спасибо', opts: ['Спасибо', 'Пожалуйста', 'Извини', 'Не за что'] },
      { q: 'Как сказать «ты тоже красивый»?', a: 'Sen de yakışıklısın', opts: ['Sen de yakışıklısın', 'Çok güzelsin', 'Nasılsın', 'Görüşürüz'] },
    ],
    reward: { xp: 50, badge: '😊', readiness: 2 },
  },
  {
    id: 6, level: 'A1', emoji: '📞', title: 'Голосовые и звонки',
    goal: 'Турки обожают голосовые. Научись назначать звонок.',
    wordIds: [49, 50, 51, 48, 98, 84],
    verbIds: [13, 2], grammarId: 4, phraseIds: [24, 25, 28],
    dialog: [
      { s: 'he', tr: 'Sesini özledim, arayabilir miyim?', ru: 'Скучаю по твоему голосу, можно позвонить?' },
      { s: 'you', tr: 'Tabii ki! Beni ara 📞', ru: 'Конечно! Позвони мне' },
      { s: 'he', tr: 'Görüntülü mü sesli mi?', ru: 'Видео или аудио?' },
      { s: 'choose', q: 'Выбери видеозвонок', options: [
        { tr: 'Görüntülü arayalım 📹', ru: 'Давай по видео', correct: true },
        { tr: 'Hiç arama', ru: 'Не звони вообще', correct: false },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Beni ara lütfen', ru: 'Позвони мне, пожалуйста' },
    test: [
      { q: 'Aramak', a: 'Звонить', opts: ['Звонить', 'Писать', 'Ждать', 'Идти'] },
      { q: 'Sesli mesaj', a: 'Голосовое сообщение', opts: ['Голосовое сообщение', 'Видеозвонок', 'Фото', 'Письмо'] },
      { q: 'Görüntülü aramak', a: 'Видеозвонок', opts: ['Видеозвонок', 'Голосовое', 'Смс', 'Чат'] },
      { q: 'Sesini özledim', a: 'Скучаю по твоему голосу', opts: ['Скучаю по твоему голосу', 'Люблю твой голос', 'Слышу тебя', 'Звоню тебе'] },
      { q: 'Как сказать «позвони мне»?', a: 'Beni ara', opts: ['Beni ara', 'Bana yaz', 'Gel buraya', 'Bekle'] },
    ],
    reward: { xp: 50, badge: '📞', readiness: 2 },
  },
  {
    id: 7, level: 'A1', emoji: '🍽️', title: 'В кафе вместе',
    goal: 'Закажи еду и напитки на вашем свидании в кафе.',
    wordIds: [384, 385, 386, 407, 408, 326],
    verbIds: [11, 12], grammarId: 4, phraseIds: [12, 13],
    dialog: [
      { s: 'he', tr: 'Ne içmek istersin?', ru: 'Что будешь пить?' },
      { s: 'you', tr: 'Bir Türk kahvesi lütfen', ru: 'Один турецкий кофе, пожалуйста' },
      { s: 'he', tr: 'Yemek de ister misin?', ru: 'Хочешь и поесть?' },
      { s: 'choose', q: 'Закажи десерт', options: [
        { tr: 'Bir tatlı alalım 🍰', ru: 'Возьмём десерт', correct: true },
        { tr: 'Hesap lütfen', ru: 'Счёт, пожалуйста', correct: false },
        { tr: 'Gitmek istiyorum', ru: 'Хочу уйти', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bir Türk kahvesi lütfen', ru: 'Один турецкий кофе, пожалуйста' },
    test: [
      { q: 'Ne içmek istersin?', a: 'Что будешь пить?', opts: ['Что будешь пить?', 'Что будешь есть?', 'Куда пойдём?', 'Который час?'] },
      { q: 'Hesap lütfen', a: 'Счёт, пожалуйста', opts: ['Счёт, пожалуйста', 'Меню, пожалуйста', 'Воды, пожалуйста', 'Помогите'] },
      { q: 'Restoran', a: 'Ресторан', opts: ['Ресторан', 'Магазин', 'Банк', 'Аптека'] },
      { q: 'yemek', a: 'есть / еда', opts: ['есть / еда', 'пить', 'спать', 'идти'] },
      { q: 'Türk kahvesi', a: 'Турецкий кофе', opts: ['Турецкий кофе', 'Чай', 'Сок', 'Вода'] },
    ],
    reward: { xp: 60, badge: '🍽️', readiness: 3 },
  },
  {
    id: 8, level: 'A1', emoji: '🛍️', title: 'Вместе по магазинам',
    goal: 'Спроси цену, попроси скидку, расплатись.',
    wordIds: [342, 344, 345, 346, 347, 349],
    verbIds: [9, 14], grammarId: 5, phraseIds: [53],
    dialog: [
      { s: 'you', tr: 'Bu ne kadar?', ru: 'Сколько это стоит?' },
      { s: 'he', tr: 'Yüz lira', ru: 'Сто лир' },
      { s: 'you', tr: 'Biraz pahalı, indirim var mı?', ru: 'Дороговато, есть скидка?' },
      { s: 'choose', q: 'Расплатись картой', options: [
        { tr: 'Kartla ödeyebilir miyim?', ru: 'Можно картой?', correct: true },
        { tr: 'Çok güzel', ru: 'Очень красиво', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bu ne kadar', ru: 'Сколько это стоит?' },
    test: [
      { q: 'Bu ne kadar?', a: 'Сколько это стоит?', opts: ['Сколько это стоит?', 'Что это?', 'Где это?', 'Чьё это?'] },
      { q: 'Pahalı', a: 'Дорогой', opts: ['Дорогой', 'Дешёвый', 'Красивый', 'Большой'] },
      { q: 'İndirim', a: 'Скидка', opts: ['Скидка', 'Цена', 'Деньги', 'Карта'] },
      { q: 'Ucuz', a: 'Дешёвый', opts: ['Дешёвый', 'Дорогой', 'Новый', 'Старый'] },
      { q: 'Как спросить про скидку?', a: 'İndirim var mı?', opts: ['İndirim var mı?', 'Ne kadar?', 'Nerede?', 'Kim?'] },
    ],
    reward: { xp: 50, badge: '🛍️', readiness: 2 },
  },
  {
    id: 9, level: 'A1', emoji: '🚕', title: 'Такси и транспорт',
    goal: 'Объясни водителю, куда ехать, и доберись сама.',
    wordIds: [372, 373, 374, 375, 376],
    verbIds: [3, 2], grammarId: 5, phraseIds: [],
    dialog: [
      { s: 'you', tr: 'Taksim\'e gitmek istiyorum', ru: 'Хочу поехать в Таксим' },
      { s: 'he', tr: 'Tabii, buyurun', ru: 'Конечно, садитесь' },
      { s: 'you', tr: 'Ne kadar sürer?', ru: 'Сколько займёт?' },
      { s: 'choose', q: 'Попроси остановить здесь', options: [
        { tr: 'Burada durabilir misiniz?', ru: 'Можете остановить здесь?', correct: true },
        { tr: 'Çok hızlı', ru: 'Очень быстро', correct: false },
        { tr: 'Teşekkürler', ru: 'Спасибо', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Taksime gitmek istiyorum', ru: 'Хочу поехать в Таксим' },
    test: [
      { q: 'Taksi', a: 'Такси', opts: ['Такси', 'Автобус', 'Метро', 'Поезд'] },
      { q: 'gitmek', a: 'идти / ехать', opts: ['идти / ехать', 'приходить', 'ждать', 'стоять'] },
      { q: 'Otobüs', a: 'Автобус', opts: ['Автобус', 'Такси', 'Машина', 'Метро'] },
      { q: 'Ne kadar sürer?', a: 'Сколько займёт?', opts: ['Сколько займёт?', 'Сколько стоит?', 'Где это?', 'Куда едем?'] },
      { q: 'Как сказать «остановите здесь»?', a: 'Burada durun', opts: ['Burada durun', 'Hızlı gidin', 'Sağa dönün', 'Bekleyin'] },
    ],
    reward: { xp: 50, badge: '🚕', readiness: 2 },
  },
  {
    id: 10, level: 'A1', emoji: '❤️', title: 'Признание в чувствах',
    goal: 'Самый важный момент — скажи о своих чувствах.',
    wordIds: [19, 20, 1, 60, 21, 87],
    verbIds: [6, 5], grammarId: 4, phraseIds: [7, 10, 19],
    dialog: [
      { s: 'he', tr: 'Sana bir şey söylemek istiyorum...', ru: 'Хочу тебе кое-что сказать...' },
      { s: 'he', tr: 'Seni seviyorum ❤️', ru: 'Я тебя люблю' },
      { s: 'choose', q: 'Признайся в ответ', options: [
        { tr: 'Ben de seni seviyorum 💕', ru: 'Я тоже тебя люблю', correct: true },
        { tr: 'Teşekkürler', ru: 'Спасибо', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
      { s: 'he', tr: 'Sen benim hayatımsın', ru: 'Ты моя жизнь' },
    ],
    game: { type: 'build', tr: 'Ben de seni seviyorum', ru: 'Я тоже тебя люблю' },
    test: [
      { q: 'Seni seviyorum', a: 'Я тебя люблю', opts: ['Я тебя люблю', 'Я по тебе скучаю', 'Я думаю о тебе', 'Я тебя жду'] },
      { q: 'Aşk', a: 'Любовь', opts: ['Любовь', 'Дружба', 'Жизнь', 'Сердце'] },
      { q: 'Sana aşığım', a: 'Я влюблён в тебя', opts: ['Я влюблён в тебя', 'Я скучаю', 'Я рад', 'Я устал'] },
      { q: 'Gerçek aşk', a: 'Настоящая любовь', opts: ['Настоящая любовь', 'Первая любовь', 'Старая любовь', 'Тайная любовь'] },
      { q: 'Как ответить «я тоже тебя люблю»?', a: 'Ben de seni seviyorum', opts: ['Ben de seni seviyorum', 'Seni özledim', 'İyi geceler', 'Teşekkürler'] },
    ],
    reward: { xp: 70, badge: '❤️', readiness: 4 },
  },
  {
    id: 11, level: 'A1', emoji: '🗓️', title: 'Планы на выходные',
    goal: 'Договоритесь, как провести выходные вместе.',
    wordIds: [383, 387, 390, 419, 54],
    verbIds: [4, 1], grammarId: 4, phraseIds: [56, 59],
    dialog: [
      { s: 'he', tr: 'Hafta sonu ne yapalım?', ru: 'Что будем делать на выходных?' },
      { s: 'you', tr: 'Bir film izleyelim mi?', ru: 'Посмотрим фильм?' },
      { s: 'he', tr: 'Olur! Veya gezeriz', ru: 'Давай! Или погуляем' },
      { s: 'choose', q: 'Предложи прогулку', options: [
        { tr: 'Deniz kenarına gidelim 🌊', ru: 'Поедем к морю', correct: true },
        { tr: 'Çalışmam lazım', ru: 'Мне надо работать', correct: false },
        { tr: 'Yorgunum', ru: 'Я устала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Hafta sonu ne yapalım', ru: 'Что будем делать на выходных?' },
    test: [
      { q: 'Hafta sonu', a: 'Выходные', opts: ['Выходные', 'Понедельник', 'Утро', 'Вечер'] },
      { q: 'Gezmek', a: 'Гулять', opts: ['Гулять', 'Работать', 'Спать', 'Готовить'] },
      { q: 'Sinema', a: 'Кино', opts: ['Кино', 'Театр', 'Музей', 'Парк'] },
      { q: 'yapmak', a: 'делать', opts: ['делать', 'идти', 'видеть', 'хотеть'] },
      { q: 'Как предложить «посмотрим фильм»?', a: 'Film izleyelim mi?', opts: ['Film izleyelim mi?', 'Ne yapalım?', 'Nereye gidelim?', 'Yorgun musun?'] },
    ],
    reward: { xp: 50, badge: '🗓️', readiness: 2 },
  },
  {
    id: 12, level: 'A1', emoji: '🎁', title: 'Праздники и подарки',
    goal: 'Поздравь его и выбери подарок к особому дню.',
    wordIds: [212, 195, 215, 214, 73],
    verbIds: [9, 10], grammarId: 5, phraseIds: [36, 46],
    dialog: [
      { s: 'he', tr: 'Bugün doğum günüm 🎂', ru: 'Сегодня мой день рождения' },
      { s: 'choose', q: 'Поздравь его', options: [
        { tr: 'İyi ki doğdun! 🎉', ru: 'С днём рождения!', correct: true },
        { tr: 'Geçmiş olsun', ru: 'Выздоравливай', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
      { s: 'he', tr: 'Çok teşekkür ederim canım 🥰', ru: 'Большое спасибо, дорогая' },
      { s: 'you', tr: 'Sana bir hediye aldım', ru: 'Я купила тебе подарок' },
    ],
    game: { type: 'build', tr: 'İyi ki doğdun', ru: 'С днём рождения' },
    test: [
      { q: 'Doğum günü', a: 'День рождения', opts: ['День рождения', 'Новый год', 'Свадьба', 'Праздник'] },
      { q: 'İyi ki doğdun', a: 'С днём рождения', opts: ['С днём рождения', 'С Новым годом', 'Поздравляю', 'Выздоравливай'] },
      { q: 'Hediye', a: 'Подарок', opts: ['Подарок', 'Цветы', 'Торт', 'Открытка'] },
      { q: 'Bayram', a: 'Праздник', opts: ['Праздник', 'Будни', 'Выходной', 'Отпуск'] },
      { q: 'Как сказать «я купила подарок»?', a: 'Hediye aldım', opts: ['Hediye aldım', 'Hediye verdim', 'Çiçek aldım', 'Teşekkürler'] },
    ],
    reward: { xp: 60, badge: '🎁', readiness: 3 },
  },

  // ===== A2 «Daha Yakın» — миссии 13–24 =====
  {
    id: 13, level: 'A2', emoji: '👨‍👩‍👧', title: 'Знакомство с родителями',
    goal: 'Большой шаг! Произведи впечатление на его родителей.',
    wordIds: [161, 162, 163, 184, 185, 186, 192],
    verbIds: [17, 13], grammarId: 9, phraseIds: [31, 33, 34],
    dialog: [
      { s: 'he', tr: 'Anne, baba, bu Ksenia', ru: 'Мама, папа, это Ксения' },
      { s: 'he', tr: 'Hoş geldin kızım', ru: 'Добро пожаловать, дочка' },
      { s: 'choose', q: 'Ответь вежливо', options: [
        { tr: 'Hoş bulduk, çok memnun oldum', ru: 'Спасибо, очень приятно', correct: true },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
        { tr: 'Anlamıyorum', ru: 'Не понимаю', correct: false },
      ]},
      { s: 'he', tr: 'Nasılsınız? İyi misiniz?', ru: 'Как вы? Всё хорошо?' },
    ],
    game: { type: 'build', tr: 'Hoş bulduk efendim', ru: 'Спасибо (ответ на приветствие)' },
    test: [
      { q: 'Hoş geldiniz', a: 'Добро пожаловать', opts: ['Добро пожаловать', 'До свидания', 'Спасибо', 'Извините'] },
      { q: 'Hoş bulduk', a: 'Рады (ответ)', opts: ['Рады (ответ)', 'Доброе утро', 'Как дела?', 'Приятного аппетита'] },
      { q: 'Anne', a: 'Мама', opts: ['Мама', 'Папа', 'Сестра', 'Бабушка'] },
      { q: 'Nasılsınız?', a: 'Как вы? (вежливо)', opts: ['Как вы? (вежливо)', 'Как ты?', 'Кто вы?', 'Где вы?'] },
      { q: 'К старшим обращаются на...', a: 'siz', opts: ['siz', 'sen', 'o', 'ben'] },
    ],
    reward: { xp: 70, badge: '👨‍👩‍👧', readiness: 4 },
  },
  {
    id: 14, level: 'A2', emoji: '🫖', title: 'Чай со свекровью',
    goal: 'Чай — это ритуал. Заведи тёплый разговор за столом.',
    wordIds: [173, 202, 192, 187, 188, 191],
    verbIds: [12, 10], grammarId: 8, phraseIds: [37, 35],
    dialog: [
      { s: 'he', tr: 'Çay ister misin kızım?', ru: 'Хочешь чаю, дочка?' },
      { s: 'you', tr: 'Evet, çok isterim, teşekkürler', ru: 'Да, очень хочу, спасибо' },
      { s: 'he', tr: 'Maşallah, Türkçen çok güzel', ru: 'МашаАллах, у тебя прекрасный турецкий' },
      { s: 'choose', q: 'Ответь скромно', options: [
        { tr: 'Sağ olun, öğreniyorum', ru: 'Спасибо, учусь', correct: true },
        { tr: 'Biliyorum', ru: 'Знаю', correct: false },
        { tr: 'Hayır', ru: 'Нет', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Çay çok güzel', ru: 'Чай очень вкусный' },
    test: [
      { q: 'Kayınvalide', a: 'Свекровь', opts: ['Свекровь', 'Золовка', 'Тётя', 'Бабушка'] },
      { q: 'Maşallah', a: 'Восхищение (от сглаза)', opts: ['Восхищение (от сглаза)', 'Спасибо', 'Извини', 'Пока'] },
      { q: 'Sağ olun', a: 'Благодарю (старшим)', opts: ['Благодарю (старшим)', 'Пожалуйста', 'Привет', 'Конечно'] },
      { q: 'Çay demlemek', a: 'Заваривать чай', opts: ['Заваривать чай', 'Пить кофе', 'Готовить еду', 'Мыть посуду'] },
      { q: '«Я дома» — это...', a: 'Evdeyim', opts: ['Evdeyim', 'Eve gidiyorum', 'Ev güzel', 'Evim'] },
    ],
    reward: { xp: 60, badge: '🫖', readiness: 3 },
  },
  {
    id: 15, level: 'A2', emoji: '🍲', title: 'За турецким столом',
    goal: 'Похвали еду правильно — и станешь любимой невесткой.',
    wordIds: [180, 181, 182, 183, 204, 326],
    verbIds: [11, 6], grammarId: 6, phraseIds: [32, 35],
    dialog: [
      { s: 'he', tr: 'Afiyet olsun, buyurun', ru: 'Приятного аппетита, угощайтесь' },
      { s: 'you', tr: 'Çok güzel olmuş, ellerinize sağlık', ru: 'Очень вкусно, здоровья вашим рукам' },
      { s: 'he', tr: 'Afiyet olsun kızım, biraz daha?', ru: 'На здоровье, дочка, ещё немного?' },
      { s: 'choose', q: 'Откажись вежливо', options: [
        { tr: 'Çok teşekkürler, doydum', ru: 'Спасибо большое, я наелась', correct: true },
        { tr: 'Hayır istemiyorum', ru: 'Нет, не хочу', correct: false },
        { tr: 'Pahalı', ru: 'Дорого', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Ellerinize sağlık', ru: 'Здоровья вашим рукам' },
    test: [
      { q: 'Elinize sağlık', a: 'Здоровья вашим рукам (после еды)', opts: ['Здоровья вашим рукам (после еды)', 'Приятного аппетита', 'Спокойной ночи', 'Добро пожаловать'] },
      { q: 'Afiyet olsun', a: 'Приятного аппетита', opts: ['Приятного аппетита', 'На здоровье', 'Спасибо', 'Пожалуйста'] },
      { q: 'Çok güzel olmuş', a: 'Получилось очень вкусно', opts: ['Получилось очень вкусно', 'Очень дорого', 'Очень красиво', 'Очень много'] },
      { q: 'Börek', a: 'Бёрек (пирог)', opts: ['Бёрек (пирог)', 'Чай', 'Суп', 'Салат'] },
      { q: '«Я поел» в прошедшем — это...', a: 'yedim', opts: ['yedim', 'yiyorum', 'yerim', 'yiyeceğim'] },
    ],
    reward: { xp: 60, badge: '🍲', readiness: 3 },
  },
  {
    id: 16, level: 'A2', emoji: '🏠', title: 'Совместный быт',
    goal: 'Распределите домашние дела и обсудите день.',
    wordIds: [356, 357, 358, 400, 401, 366],
    verbIds: [4, 18], grammarId: 8, phraseIds: [52, 53],
    dialog: [
      { s: 'he', tr: 'Bugün işten geç geldim, yorgunum', ru: 'Сегодня поздно пришёл с работы, устал' },
      { s: 'you', tr: 'Geçmiş olsun canım, yemek hazır', ru: 'Отдохни, дорогой, еда готова' },
      { s: 'choose', q: 'Предложи помощь', options: [
        { tr: 'Bulaşıkları ben yıkarım', ru: 'Я помою посуду', correct: true },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
        { tr: 'Yorgunum', ru: 'Я устала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Yemek hazır', ru: 'Еда готова' },
    test: [
      { q: 'Mutfak', a: 'Кухня', opts: ['Кухня', 'Спальня', 'Ванная', 'Балкон'] },
      { q: 'Temizlik yapmak', a: 'Делать уборку', opts: ['Делать уборку', 'Готовить', 'Стирать', 'Гладить'] },
      { q: 'İş', a: 'Работа', opts: ['Работа', 'Дом', 'Школа', 'Магазин'] },
      { q: 'Yatak odası', a: 'Спальня', opts: ['Спальня', 'Кухня', 'Гостиная', 'Ванная'] },
      { q: '«На работе» — это...', a: 'işte', opts: ['işte', 'işe', 'işim', 'iş'] },
    ],
    reward: { xp: 60, badge: '🏠', readiness: 3 },
  },
  {
    id: 17, level: 'A2', emoji: '😤', title: 'Ревность',
    goal: 'Ревность — часть турецких отношений. Научись отвечать спокойно.',
    wordIds: [101, 102, 103, 106, 129, 110],
    verbIds: [7, 13], grammarId: 6, phraseIds: [41, 46],
    dialog: [
      { s: 'he', tr: 'Bu kim? Kiminle konuşuyorsun?', ru: 'Кто это? С кем ты разговариваешь?' },
      { s: 'you', tr: 'Sadece bir arkadaş, merak etme', ru: 'Просто друг, не переживай' },
      { s: 'choose', q: 'Успокой его', options: [
        { tr: 'Sana güveniyorum, sen de bana güven', ru: 'Я тебе доверяю, и ты мне доверяй', correct: true },
        { tr: 'Seni sevmiyorum', ru: 'Я тебя не люблю', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Merak etme canım', ru: 'Не переживай, дорогой' },
    test: [
      { q: 'Kıskanmak', a: 'Ревновать', opts: ['Ревновать', 'Скучать', 'Злиться', 'Доверять'] },
      { q: 'Sadece arkadaş', a: 'Просто друг', opts: ['Просто друг', 'Мой парень', 'Мой брат', 'Сосед'] },
      { q: 'Merak etme', a: 'Не переживай', opts: ['Не переживай', 'Не злись', 'Не уходи', 'Не плачь'] },
      { q: 'Güvenmek', a: 'Доверять', opts: ['Доверять', 'Ревновать', 'Любить', 'Ждать'] },
      { q: 'Kiminle?', a: 'С кем?', opts: ['С кем?', 'Где?', 'Когда?', 'Почему?'] },
    ],
    reward: { xp: 60, badge: '😤', readiness: 3 },
  },
  {
    id: 18, level: 'A2', emoji: '🤝', title: 'Примирение',
    goal: 'После ссоры — помиритесь по-турецки тепло.',
    wordIds: [74, 75, 77, 79, 127, 150],
    verbIds: [8, 5], grammarId: 6, phraseIds: [44, 45, 48],
    dialog: [
      { s: 'he', tr: 'Özür dilerim, haklısın', ru: 'Извини, ты права' },
      { s: 'you', tr: 'Ben de üzgünüm, barışalım', ru: 'Я тоже расстроена, давай помиримся' },
      { s: 'choose', q: 'Заверши примирение', options: [
        { tr: 'Seni çok seviyorum, geçti', ru: 'Я тебя очень люблю, всё прошло', correct: true },
        { tr: 'Hâlâ kızgınım', ru: 'Я всё ещё злюсь', correct: false },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Gel barışalım', ru: 'Давай помиримся' },
    test: [
      { q: 'Özür dilerim', a: 'Извини', opts: ['Извини', 'Спасибо', 'Пожалуйста', 'Прощай'] },
      { q: 'Barışmak', a: 'Помириться', opts: ['Помириться', 'Поссориться', 'Расстаться', 'Встретиться'] },
      { q: 'Haklısın', a: 'Ты права/прав', opts: ['Ты права/прав', 'Ты ошибаешься', 'Ты красивая', 'Ты добрая'] },
      { q: 'Üzgünüm', a: 'Мне жаль', opts: ['Мне жаль', 'Я рад', 'Я устал', 'Я зол'] },
      { q: '«Прости меня» (эмоц.) — это...', a: 'Affet beni', opts: ['Affet beni', 'Teşekkürler', 'Görüşürüz', 'Hoşça kal'] },
    ],
    reward: { xp: 70, badge: '🤝', readiness: 4 },
  },
  {
    id: 19, level: 'A2', emoji: '🏥', title: 'У врача',
    goal: 'Объясни врачу, что болит, и пойми назначение.',
    wordIds: [377, 378, 381, 382, 380, 200],
    verbIds: [1, 17], grammarId: 7, phraseIds: [],
    dialog: [
      { s: 'he', tr: 'Geçmiş olsun, neyiniz var?', ru: 'Выздоравливайте, что беспокоит?' },
      { s: 'you', tr: 'Başım ağrıyor ve ateşim var', ru: 'Болит голова и температура' },
      { s: 'choose', q: 'Спроси про лекарство', options: [
        { tr: 'Hangi ilacı kullanmalıyım?', ru: 'Какое лекарство принимать?', correct: true },
        { tr: 'Çok pahalı', ru: 'Очень дорого', correct: false },
        { tr: 'Teşekkürler görüşürüz', ru: 'Спасибо, увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Başım ağrıyor', ru: 'У меня болит голова' },
    test: [
      { q: 'Doktor', a: 'Врач', opts: ['Врач', 'Аптекарь', 'Медсестра', 'Сосед'] },
      { q: 'Hastane', a: 'Больница', opts: ['Больница', 'Аптека', 'Школа', 'Банк'] },
      { q: 'Başım ağrıyor', a: 'У меня болит голова', opts: ['У меня болит голова', 'Я устал', 'Мне холодно', 'Я голоден'] },
      { q: 'Geçmiş olsun', a: 'Выздоравливайте', opts: ['Выздоравливайте', 'Приятного аппетита', 'Добро пожаловать', 'Поздравляю'] },
      { q: 'İlaç', a: 'Лекарство', opts: ['Лекарство', 'Витамин', 'Чай', 'Вода'] },
    ],
    reward: { xp: 60, badge: '🏥', readiness: 3 },
  },
  {
    id: 20, level: 'A2', emoji: '💊', title: 'В аптеке',
    goal: 'Купи лекарство и пойми, как его принимать.',
    wordIds: [379, 380, 381, 382, 344, 200],
    verbIds: [9, 12], grammarId: 7, phraseIds: [],
    dialog: [
      { s: 'you', tr: 'Baş ağrısı için bir şey var mı?', ru: 'Есть что-нибудь от головной боли?' },
      { s: 'he', tr: 'Evet, bu hapı günde iki kez için', ru: 'Да, эту таблетку дважды в день' },
      { s: 'choose', q: 'Уточни и поблагодари', options: [
        { tr: 'Anladım, teşekkür ederim', ru: 'Поняла, спасибо', correct: true },
        { tr: 'Çok güzelsin', ru: 'Ты красивый', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bir şey var mı', ru: 'Есть что-нибудь?' },
    test: [
      { q: 'Eczane', a: 'Аптека', opts: ['Аптека', 'Больница', 'Магазин', 'Банк'] },
      { q: 'İlaç aldım', a: 'Я купила лекарство', opts: ['Я купила лекарство', 'Я выпила чай', 'Я пошла домой', 'Я устала'] },
      { q: 'Hasta', a: 'Больной', opts: ['Больной', 'Здоровый', 'Усталый', 'Голодный'] },
      { q: 'Günde iki kez', a: 'Дважды в день', opts: ['Дважды в день', 'Раз в неделю', 'Каждый час', 'По утрам'] },
      { q: '«Есть что-нибудь?» — это...', a: 'Bir şey var mı?', opts: ['Bir şey var mı?', 'Ne kadar?', 'Nerede?', 'Kim?'] },
    ],
    reward: { xp: 60, badge: '💊', readiness: 3 },
  },
  {
    id: 21, level: 'A2', emoji: '🏘️', title: 'Соседи и район',
    goal: 'Познакомься с соседями — в Турции это важно.',
    wordIds: [353, 354, 352, 403, 404, 192],
    verbIds: [14, 1], grammarId: 8, phraseIds: [],
    dialog: [
      { s: 'he', tr: 'Merhaba, ben üst kattaki komşunuz', ru: 'Здравствуйте, я ваш сосед сверху' },
      { s: 'you', tr: 'Memnun oldum! Hoş geldiniz', ru: 'Приятно! Добро пожаловать' },
      { s: 'choose', q: 'Пригласи на чай', options: [
        { tr: 'Bir gün çaya buyurun', ru: 'Заходите как-нибудь на чай', correct: true },
        { tr: 'Gitmem lazım', ru: 'Мне надо идти', correct: false },
        { tr: 'Anlamıyorum', ru: 'Не понимаю', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Çaya buyurun', ru: 'Приходите на чай' },
    test: [
      { q: 'Komşu', a: 'Сосед', opts: ['Сосед', 'Друг', 'Брат', 'Гость'] },
      { q: 'Daire', a: 'Квартира', opts: ['Квартира', 'Дом', 'Комната', 'Балкон'] },
      { q: 'Kira', a: 'Аренда', opts: ['Аренда', 'Цена', 'Скидка', 'Деньги'] },
      { q: 'Pazar', a: 'Рынок / воскресенье', opts: ['Рынок / воскресенье', 'Магазин', 'Базар', 'Площадь'] },
      { q: '«У соседа» — это...', a: 'komşuda', opts: ['komşuda', 'komşuya', 'komşum', 'komşu'] },
    ],
    reward: { xp: 50, badge: '🏘️', readiness: 3 },
  },
  {
    id: 22, level: 'A2', emoji: '🌙', title: 'Байрам и праздники',
    goal: 'Поздравь семью с праздником и соблюди традиции.',
    wordIds: [195, 196, 199, 188, 190, 215],
    verbIds: [2, 10], grammarId: 7, phraseIds: [36, 46],
    dialog: [
      { s: 'he', tr: 'Bayramın mübarek olsun canım', ru: 'С праздником, дорогая' },
      { s: 'you', tr: 'Senin de bayramın mübarek olsun', ru: 'И тебя с праздником' },
      { s: 'choose', q: 'Прояви уважение к старшим', options: [
        { tr: 'Büyüklerin elini öpelim', ru: 'Поцелуем руки старшим', correct: true },
        { tr: 'Eve gidelim', ru: 'Пойдём домой', correct: false },
        { tr: 'Yorgunum', ru: 'Я устала', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Bayramın mübarek olsun', ru: 'С праздником' },
    test: [
      { q: 'Bayram', a: 'Праздник', opts: ['Праздник', 'Свадьба', 'Будни', 'Отпуск'] },
      { q: 'El öpmek', a: 'Целовать руку (уважение)', opts: ['Целовать руку (уважение)', 'Махать рукой', 'Пожимать руку', 'Обниматься'] },
      { q: 'İnşallah', a: 'Если Бог даст', opts: ['Если Бог даст', 'Слава Богу', 'Боже мой', 'С праздником'] },
      { q: 'Kurban Bayramı', a: 'Курбан-байрам', opts: ['Курбан-байрам', 'Новый год', 'День рождения', 'Свадьба'] },
      { q: 'Hediye almak', a: 'Купить подарок', opts: ['Купить подарок', 'Дать подарок', 'Получить письмо', 'Поздравить'] },
    ],
    reward: { xp: 60, badge: '🌙', readiness: 3 },
  },
  {
    id: 23, level: 'A2', emoji: '💍', title: 'Помолвка (Nişan)',
    goal: 'Особый момент — помолвка по турецким традициям.',
    wordIds: [245, 246, 247, 248, 28, 23],
    verbIds: [5, 1], grammarId: 9, phraseIds: [],
    dialog: [
      { s: 'he', tr: 'Seninle nişanlanmak istiyorum', ru: 'Хочу с тобой обручиться' },
      { s: 'you', tr: 'Çok mutluyum, evet!', ru: 'Я так счастлива, да!' },
      { s: 'he', tr: 'Yüzüğü takıyorum, artık nişanlıyız', ru: 'Надеваю кольцо, теперь мы помолвлены' },
      { s: 'choose', q: 'Вырази радость', options: [
        { tr: 'Hayatımın en güzel günü 💍', ru: 'Самый счастливый день в жизни', correct: true },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
        { tr: 'Pahalı', ru: 'Дорого', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Artık nişanlıyız', ru: 'Теперь мы помолвлены' },
    test: [
      { q: 'Nişan', a: 'Помолвка', opts: ['Помолвка', 'Свадьба', 'Развод', 'Свидание'] },
      { q: 'Nişan yüzüğü', a: 'Кольцо помолвки', opts: ['Кольцо помолвки', 'Серьги', 'Браслет', 'Цепочка'] },
      { q: 'Nişanlandık', a: 'Мы помолвлены', opts: ['Мы помолвлены', 'Мы поженились', 'Мы расстались', 'Мы встретились'] },
      { q: 'Nişanlı', a: 'Жених/невеста', opts: ['Жених/невеста', 'Муж/жена', 'Друг', 'Сосед'] },
      { q: '«Моя помолвленная» — это...', a: 'nişanlım', opts: ['nişanlım', 'nişanlın', 'nişan', 'nişanlı'] },
    ],
    reward: { xp: 70, badge: '💍', readiness: 4 },
  },
  {
    id: 24, level: 'A2', emoji: '🧿', title: 'Традиции и суеверия',
    goal: 'Пойми турецкие традиции, чтобы не попасть впросак.',
    wordIds: [187, 188, 209, 210, 192, 190],
    verbIds: [17, 7], grammarId: 9, phraseIds: [40],
    dialog: [
      { s: 'he', tr: 'Nazar değmesin diye nazar boncuğu taktık', ru: 'Повесили глаз от сглаза' },
      { s: 'you', tr: 'Çok güzel bir gelenek', ru: 'Очень красивая традиция' },
      { s: 'choose', q: 'Похвали по-турецки', options: [
        { tr: 'Maşallah, çok güzel', ru: 'МашаАллах, очень красиво', correct: true },
        { tr: 'Bilmiyorum', ru: 'Не знаю', correct: false },
        { tr: 'Görüşürüz', ru: 'Увидимся', correct: false },
      ]},
    ],
    game: { type: 'build', tr: 'Çok güzel bir gelenek', ru: 'Очень красивая традиция' },
    test: [
      { q: 'Maşallah', a: 'Защита от сглаза / восхищение', opts: ['Защита от сглаза / восхищение', 'Спасибо', 'Извини', 'Привет'] },
      { q: 'Geleneksel', a: 'Традиционный', opts: ['Традиционный', 'Современный', 'Новый', 'Старый'] },
      { q: 'Büyüklere saygı', a: 'Уважение к старшим', opts: ['Уважение к старшим', 'Любовь к детям', 'Помощь соседям', 'Дружба'] },
      { q: 'İnşallah', a: 'Если Бог даст', opts: ['Если Бог даст', 'Слава Богу', 'С праздником', 'Боже мой'] },
      { q: 'Nazar boncuğu', a: 'Оберег от сглаза', opts: ['Оберег от сглаза', 'Кольцо', 'Подарок', 'Сувенир'] },
    ],
    reward: { xp: 70, badge: '🧿', readiness: 4 },
  },
];

const A1_EXAM = {
  level: 'A1',
  title: 'Экзамен A1 «İlk Adımlar»',
  pass: 70,
  questions: [
    { sec: 'Лексика', q: 'Aşkım', a: 'Любовь моя', opts: ['Любовь моя', 'Друг мой', 'Брат', 'Сосед'] },
    { sec: 'Лексика', q: 'Buluşma', a: 'Свидание', opts: ['Свидание', 'Работа', 'Магазин', 'Дорога'] },
    { sec: 'Лексика', q: 'İndirim', a: 'Скидка', opts: ['Скидка', 'Цена', 'Деньги', 'Чек'] },
    { sec: 'Грамматика', q: '«Я думаю» — это...', a: 'düşünüyorum', opts: ['düşünüyorum', 'düşünüyorsun', 'düşünüyor', 'düşündüm'] },
    { sec: 'Грамматика', q: 'Отрицание «не понимаю»', a: 'anlamıyorum', opts: ['anlamıyorum', 'anlıyorum', 'anladım', 'anlarım'] },
    { sec: 'Грамматика', q: 'Вопрос «выпьем кофе?»', a: 'Kahve içelim mi?', opts: ['Kahve içelim mi?', 'Kahve içiyorum', 'Kahve istemiyorum', 'Kahve güzel'] },
    { sec: 'Чтение', q: '«Bu akşam müsait misin?» означает...', a: 'Ты свободна сегодня вечером?', opts: ['Ты свободна сегодня вечером?', 'Что ты делаешь?', 'Где ты живёшь?', 'Как тебя зовут?'] },
    { sec: 'Ситуация', q: 'Он написал «Seni seviyorum». Ответь:', a: 'Ben de seni seviyorum', opts: ['Ben de seni seviyorum', 'Görüşürüz', 'Teşekkürler', 'Anlamıyorum'] },
    { sec: 'Ситуация', q: 'В кафе хочешь кофе. Скажи:', a: 'Bir kahve lütfen', opts: ['Bir kahve lütfen', 'Hesap lütfen', 'Çok pahalı', 'Gitmek istiyorum'] },
    { sec: 'Ситуация', q: 'Поздравь с днём рождения:', a: 'İyi ki doğdun', opts: ['İyi ki doğdun', 'Geçmiş olsun', 'Güle güle', 'Afiyet olsun'] },
  ],
};

const A2_EXAM = {
  level: 'A2',
  title: 'Экзамен A2 «Daha Yakın»',
  pass: 70,
  questions: [
    { sec: 'Лексика', q: 'Kayınvalide', a: 'Свекровь', opts: ['Свекровь', 'Золовка', 'Тётя', 'Сестра'] },
    { sec: 'Лексика', q: 'Eczane', a: 'Аптека', opts: ['Аптека', 'Больница', 'Магазин', 'Банк'] },
    { sec: 'Лексика', q: 'Nişan', a: 'Помолвка', opts: ['Помолвка', 'Свадьба', 'Развод', 'Свидание'] },
    { sec: 'Грамматика', q: 'Прошедшее: «я пришёл»', a: 'geldim', opts: ['geldim', 'geliyorum', 'geleceğim', 'gelirim'] },
    { sec: 'Грамматика', q: 'Куда? «домой»', a: 'eve', opts: ['eve', 'evde', 'evim', 'ev'] },
    { sec: 'Грамматика', q: 'Где? «на работе»', a: 'işte', opts: ['işte', 'işe', 'işim', 'iş'] },
    { sec: 'Чтение', q: '«Ellerinize sağlık» говорят...', a: 'после еды (хозяйке)', opts: ['после еды (хозяйке)', 'при встрече', 'на свадьбе', 'утром'] },
    { sec: 'Ситуация', q: 'Свекровь похвалила твой турецкий. Ответь:', a: 'Sağ olun, öğreniyorum', opts: ['Sağ olun, öğreniyorum', 'Biliyorum', 'Hayır', 'Görüşürüz'] },
    { sec: 'Ситуация', q: 'Он ревнует. Успокой:', a: 'Merak etme, sana güveniyorum', opts: ['Merak etme, sana güveniyorum', 'Seni sevmiyorum', 'Görüşürüz', 'Bilmiyorum'] },
    { sec: 'Ситуация', q: 'Поздравь с праздником:', a: 'Bayramın mübarek olsun', opts: ['Bayramın mübarek olsun', 'İyi ki doğdun', 'Geçmiş olsun', 'Afiyet olsun'] },
  ],
};

const EXAMS = { A1: A1_EXAM, A2: A2_EXAM };
