const PHRASE_CATEGORIES = [
  { id: 'flirt', emoji: '💕', name: 'Флирт и знакомство', color: '#E91E63' },
  { id: 'date', emoji: '🌹', name: 'На свидании', color: '#FF5722' },
  { id: 'chat', emoji: '💬', name: 'Переписка', color: '#9C27B0' },
  { id: 'family', emoji: '👨‍👩‍👧', name: 'С его семьёй', color: '#4CAF50' },
  { id: 'conflict', emoji: '⚡', name: 'Ссоры и примирение', color: '#FF9800' },
  { id: 'daily', emoji: '☀️', name: 'Каждый день', color: '#2196F3' },
];

const PHRASES = [
  // 💕 Флирт и знакомство
  { id: 1, cat: 'flirt', tr: 'Merhaba, tanışabilir miyiz?', ru: 'Привет, можем познакомиться?', context: 'Вежливое начало разговора', situation: 'При первой встрече' },
  { id: 2, cat: 'flirt', tr: 'Seni görmek çok güzel', ru: 'Очень приятно тебя видеть', context: 'Тёплое приветствие', situation: 'При встрече' },
  { id: 3, cat: 'flirt', tr: 'Numaran nedir? Sana yazabilir miyim?', ru: 'Какой твой номер? Могу написать?', context: 'Прямой вопрос — нормально в Турции', situation: 'Конец первого разговора' },
  { id: 4, cat: 'flirt', tr: 'Bu gece ne yapıyorsun?', ru: 'Что ты делаешь сегодня вечером?', context: 'Приглашение на свидание', situation: 'В переписке' },
  { id: 5, cat: 'flirt', tr: 'Seninle vakit geçirmek çok güzel', ru: 'Проводить время с тобой — прекрасно', context: 'Комплимент после встречи', situation: 'После свидания' },
  { id: 6, cat: 'flirt', tr: 'Gülüşün çok güzel', ru: 'У тебя красивая улыбка', context: 'Популярный комплимент', situation: 'При общении' },
  { id: 7, cat: 'flirt', tr: 'Senden hoşlanıyorum', ru: 'Ты мне нравишься', context: 'Признание — серьёзный шаг', situation: 'Когда чувства взаимны' },
  { id: 8, cat: 'flirt', tr: 'Bir kahve içelim mi?', ru: 'Выпьем кофе?', context: 'Классическое приглашение', situation: 'Приглашение на встречу' },
  { id: 9, cat: 'flirt', tr: 'Türk müsün? Çok yakışıklısın', ru: 'Ты турок? Ты очень красивый', context: 'Прямой комплимент мужчине', situation: 'При знакомстве' },
  { id: 10, cat: 'flirt', tr: 'Benimle çıkar mısın?', ru: 'Пойдёшь со мной на свидание?', context: 'Официальное приглашение', situation: 'Начало отношений' },

  // 🌹 На свидании
  { id: 11, cat: 'date', tr: 'Bugün çok güzel görünüyorsun', ru: 'Сегодня ты выглядишь очень красиво', context: 'Комплимент при встрече', situation: 'Начало свидания' },
  { id: 12, cat: 'date', tr: 'Ne yemek istersin?', ru: 'Что хочешь поесть?', context: 'Забота — важна в турецкой культуре', situation: 'В ресторане' },
  { id: 13, cat: 'date', tr: 'Hesabı ben öderim', ru: 'Я заплачу за счёт', context: 'В Турции обычно платит мужчина', situation: 'Конец ужина' },
  { id: 14, cat: 'date', tr: 'Seni eve bırakayım', ru: 'Давай подвезу тебя домой', context: 'Джентльменское предложение', situation: 'После свидания' },
  { id: 15, cat: 'date', tr: 'Bu akşam harika geçti', ru: 'Этот вечер был замечательным', context: 'Благодарность за свидание', situation: 'Прощание' },
  { id: 16, cat: 'date', tr: 'Tekrar buluşalım mı?', ru: 'Встретимся ещё раз?', context: 'Предложение второго свидания', situation: 'После первой встречи' },
  { id: 17, cat: 'date', tr: 'Burası çok güzel bir yer', ru: 'Это очень красивое место', context: 'Комментарий о ресторане/кафе', situation: 'На свидании' },
  { id: 18, cat: 'date', tr: 'Yürüyüşe çıkalım mı?', ru: 'Пойдём прогуляемся?', context: 'Романтическое предложение', situation: 'После ужина' },
  { id: 19, cat: 'date', tr: 'Seninle olmak beni mutlu ediyor', ru: 'Быть с тобой делает меня счастливой', context: 'Признание чувств', situation: 'Романтический момент' },
  { id: 20, cat: 'date', tr: 'Eve iyi vardın mı?', ru: 'Ты хорошо добрался домой?', context: 'Знак заботы после свидания', situation: 'Вечером после встречи' },

  // 💬 Переписка
  { id: 21, cat: 'chat', tr: 'Günaydın canım, nasılsın?', ru: 'Доброе утро, дорогой, как ты?', context: 'Утреннее сообщение — важный ритуал', situation: 'Каждое утро' },
  { id: 22, cat: 'chat', tr: 'Ne yapıyorsun şu an?', ru: 'Что ты сейчас делаешь?', context: 'Проявление интереса', situation: 'В течение дня' },
  { id: 23, cat: 'chat', tr: 'Seni çok özledim, görüşelim mi?', ru: 'Очень скучала, увидимся?', context: 'Инициатива встречи', situation: 'Когда давно не виделись' },
  { id: 24, cat: 'chat', tr: 'Fotoğrafını at, görmek istiyorum', ru: 'Скинь фото, хочу увидеть', context: 'Турки любят фото в переписке', situation: 'В чате' },
  { id: 25, cat: 'chat', tr: 'Sesli mesaj atayım mı?', ru: 'Отправить голосовое?', context: 'Турки обожают голосовые сообщения!', situation: 'В WhatsApp' },
  { id: 26, cat: 'chat', tr: 'İyi geceler tatlım, tatlı rüyalar', ru: 'Спокойной ночи, сладкая, сладких снов', context: 'Вечерний ритуал', situation: 'Перед сном' },
  { id: 27, cat: 'chat', tr: 'Neden cevap vermiyorsun?', ru: 'Почему не отвечаешь?', context: 'Может быть тревогой или контролем', situation: 'Когда долго молчат' },
  { id: 28, cat: 'chat', tr: 'Video açalım mı?', ru: 'Включим видео?', context: 'Видеозвонок — важен для отношений на расстоянии', situation: 'Вечером' },
  { id: 29, cat: 'chat', tr: 'Bugün çok yoğundum, özür dilerim', ru: 'Сегодня был очень загружен, извини', context: 'Объяснение молчания', situation: 'После долгого ответа' },
  { id: 30, cat: 'chat', tr: 'Sana bir şey söylemem lazım', ru: 'Мне нужно тебе кое-что сказать', context: 'Серьёзный разговор впереди', situation: 'Важный момент' },

  // 👨‍👩‍👧 С его семьёй
  { id: 31, cat: 'family', tr: 'Hoş geldiniz, çok memnun oldum', ru: 'Добро пожаловать, очень рада', context: 'Приветствие при встрече с семьёй', situation: 'Первая встреча' },
  { id: 32, cat: 'family', tr: 'Elinize sağlık, çok güzel olmuş', ru: 'Здоровья вашим рукам, очень вкусно', context: 'ОБЯЗАТЕЛЬНО скажи после еды!', situation: 'За столом' },
  { id: 33, cat: 'family', tr: 'Yardım edebilir miyim?', ru: 'Могу ли я помочь?', context: 'Всегда предлагай помощь — это важно', situation: 'На кухне' },
  { id: 34, cat: 'family', tr: 'Türkçe öğreniyorum, çok zor ama güzel', ru: 'Учу турецкий, очень сложно, но красиво', context: 'Это всегда вызывает уважение', situation: 'При общении с семьёй' },
  { id: 35, cat: 'family', tr: 'Anneniz çok iyi yemek yapıyor', ru: 'Ваша мама очень вкусно готовит', context: 'Лучший комплимент маме!', situation: 'После обеда' },
  { id: 36, cat: 'family', tr: 'Bayramınız kutlu olsun', ru: 'С праздником вас', context: 'На Байрам и другие праздники', situation: 'Во время праздника' },
  { id: 37, cat: 'family', tr: 'Çay alır mısınız?', ru: 'Хотите чаю?', context: 'Предлагай чай — знак гостеприимства', situation: 'В гостях' },
  { id: 38, cat: 'family', tr: 'Ailesi çok sıcakkanlı', ru: 'Его семья очень тёплая', context: 'Комплимент о семье', situation: 'После визита' },
  { id: 39, cat: 'family', tr: 'İnşallah yakında yine görüşürüz', ru: 'Надеюсь, скоро снова увидимся', context: 'Тёплое прощание с семьёй', situation: 'При уходе' },
  { id: 40, cat: 'family', tr: 'Maşallah, ne güzel bir ev', ru: 'МашаАллах, какой красивый дом', context: 'Маşallah — говори при похвале', situation: 'В гостях' },

  // ⚡ Ссоры и примирение
  { id: 41, cat: 'conflict', tr: 'Neden bana böyle davranıyorsun?', ru: 'Почему ты так со мной обращаешься?', context: 'Выражение обиды', situation: 'Во время ссоры' },
  { id: 42, cat: 'conflict', tr: 'Bu konuyu sakin sakin konuşalım', ru: 'Давай обсудим это спокойно', context: 'Призыв к диалогу', situation: 'Начало серьёзного разговора' },
  { id: 43, cat: 'conflict', tr: 'Beni dinler misin lütfen?', ru: 'Послушаешь меня, пожалуйста?', context: 'Просьба быть услышанной', situation: 'Когда не слушают' },
  { id: 44, cat: 'conflict', tr: 'Haklısın, özür dilerim', ru: 'Ты прав(а), извини', context: 'Признание ошибки', situation: 'Примирение' },
  { id: 45, cat: 'conflict', tr: 'Seni kırdıysam çok üzgünüm', ru: 'Если я тебя обидела, мне очень жаль', context: 'Извинение с эмпатией', situation: 'После конфликта' },
  { id: 46, cat: 'conflict', tr: 'Birbirimize güvenmeliyiz', ru: 'Мы должны доверять друг другу', context: 'Основа здоровых отношений', situation: 'Серьёзный разговор' },
  { id: 47, cat: 'conflict', tr: 'Sana kızmıyorum, sadece üzgünüm', ru: 'Я не злюсь, просто мне грустно', context: 'Выражение чувств без агрессии', situation: 'Эмоциональный разговор' },
  { id: 48, cat: 'conflict', tr: 'Gel barışalım, kavga etmeyelim', ru: 'Давай помиримся, не будем ссориться', context: 'Инициатива примирения', situation: 'После ссоры' },
  { id: 49, cat: 'conflict', tr: 'Senden bir şey rica edebilir miyim?', ru: 'Могу тебя попросить кое о чём?', context: 'Мягкое начало просьбы', situation: 'Когда нужно обсудить границы' },
  { id: 50, cat: 'conflict', tr: 'Seninle her şeyin üstesinden gelebiliriz', ru: 'Вместе мы справимся со всем', context: 'Поддержка и единство', situation: 'После решения проблемы' },

  // ☀️ Каждый день
  { id: 51, cat: 'daily', tr: 'Bugün hava çok güzel, dışarı çıkalım mı?', ru: 'Сегодня отличная погода, выйдем на улицу?', context: 'Приглашение на прогулку', situation: 'Утром или днём' },
  { id: 52, cat: 'daily', tr: 'Akşam ne yiyelim?', ru: 'Что будем есть на ужин?', context: 'Ежедневный вопрос', situation: 'После работы' },
  { id: 53, cat: 'daily', tr: 'Markete gitmem lazım, bir şey ister misin?', ru: 'Мне нужно в магазин, тебе что-нибудь нужно?', context: 'Забота в быту', situation: 'Перед выходом' },
  { id: 54, cat: 'daily', tr: 'Çok yoruldum, biraz dinlenelim', ru: 'Я очень устала, давай отдохнём', context: 'Честное выражение усталости', situation: 'Вечером' },
  { id: 55, cat: 'daily', tr: 'Yarın erken kalkmam lazım', ru: 'Завтра мне нужно рано встать', context: 'Предупреждение', situation: 'Перед сном' },
  { id: 56, cat: 'daily', tr: 'Bu dizi çok güzel, birlikte izleyelim mi?', ru: 'Этот сериал очень хороший, посмотрим вместе?', context: 'Турецкие сериалы — общая тема', situation: 'Вечером дома' },
  { id: 57, cat: 'daily', tr: 'Kahvaltıyı ben hazırlarım', ru: 'Я приготовлю завтрак', context: 'Забота по утрам', situation: 'Утром' },
  { id: 58, cat: 'daily', tr: 'Trafik çok kötü, geç kalacağım', ru: 'Пробки ужасные, опоздаю', context: 'Классическая ситуация в Турции', situation: 'В дороге' },
  { id: 59, cat: 'daily', tr: 'Bu hafta sonu ne yapalım?', ru: 'Что будем делать на выходных?', context: 'Планирование вместе', situation: 'Среди недели' },
  { id: 60, cat: 'daily', tr: 'Seni almaya geliyorum', ru: 'Еду за тобой', context: 'Приятное сообщение', situation: 'Перед встречей' },
];

const FILL_EXERCISES = [
  { id: 1, sentence: 'Seni çok ___', answer: 'özledim', options: ['özledim', 'sevdim', 'kızdım', 'unuttum'], tr_full: 'Seni çok özledim', ru: 'Я очень скучал(а) по тебе' },
  { id: 2, sentence: '___ canım, nasılsın?', answer: 'Günaydın', options: ['Günaydın', 'İyi geceler', 'Görüşürüz', 'Hoş geldin'], tr_full: 'Günaydın canım, nasılsın?', ru: 'Доброе утро, дорогая, как ты?' },
  { id: 3, sentence: 'Seninle ___ istiyorum', answer: 'evlenmek', options: ['evlenmek', 'tartışmak', 'ayrılmak', 'kavga'], tr_full: 'Seninle evlenmek istiyorum', ru: 'Хочу на тебе жениться' },
  { id: 4, sentence: 'Elinize ___, çok güzel olmuş', answer: 'sağlık', options: ['sağlık', 'teşekkür', 'güzel', 'buyrun'], tr_full: 'Elinize sağlık, çok güzel olmuş', ru: 'Здоровья вашим рукам, очень вкусно' },
  { id: 5, sentence: 'Sana ___ dilerim', answer: 'özür', options: ['özür', 'teşekkür', 'hayırlı', 'güzel'], tr_full: 'Sana özür dilerim', ru: 'Извини' },
  { id: 6, sentence: 'Seni ___ etmek istemiyorum', answer: 'kaybetmek', options: ['kaybetmek', 'görmek', 'aramak', 'tanımak'], tr_full: 'Seni kaybetmek istemiyorum', ru: 'Не хочу тебя потерять' },
  { id: 7, sentence: '___ ol, konuşalım', answer: 'Sakin', options: ['Sakin', 'Sinirli', 'Kıskanç', 'Mutlu'], tr_full: 'Sakin ol, konuşalım', ru: 'Успокойся, давай поговорим' },
  { id: 8, sentence: 'Türkçe ___', answer: 'öğreniyorum', options: ['öğreniyorum', 'bilmiyorum', 'konuşmam', 'istemiyorum'], tr_full: 'Türkçe öğreniyorum', ru: 'Я учу турецкий' },
  { id: 9, sentence: 'Annem seni ___', answer: 'soruyor', options: ['soruyor', 'kızıyor', 'arıyor', 'unutuyor'], tr_full: 'Annem seni soruyor', ru: 'Мама о тебе спрашивает' },
  { id: 10, sentence: 'Senden ___ yok', answer: 'başkası', options: ['başkası', 'güzeli', 'iyisi', 'kötüsü'], tr_full: 'Senden başkası yok', ru: 'Нет никого кроме тебя' },
  { id: 11, sentence: 'Birlikte ___ verelim', answer: 'karar', options: ['karar', 'cevap', 'hediye', 'para'], tr_full: 'Birlikte karar verelim', ru: 'Давай решим вместе' },
  { id: 12, sentence: 'Bana ___ ver', answer: 'güven', options: ['güven', 'para', 'telefon', 'yemek'], tr_full: 'Bana güven ver', ru: 'Доверяй мне' },
  { id: 13, sentence: 'Hoş ___, buyrun oturun', answer: 'geldiniz', options: ['geldiniz', 'bulduk', 'gördük', 'kaldınız'], tr_full: 'Hoş geldiniz, buyrun oturun', ru: 'Добро пожаловать, проходите, садитесь' },
  { id: 14, sentence: 'Bu gece ___ izleyelim mi?', answer: 'dizi', options: ['dizi', 'haber', 'kitap', 'müzik'], tr_full: 'Bu gece dizi izleyelim mi?', ru: 'Посмотрим сериал сегодня?' },
  { id: 15, sentence: 'İyi ___ canım, tatlı rüyalar', answer: 'geceler', options: ['geceler', 'günler', 'sabahlar', 'akşamlar'], tr_full: 'İyi geceler canım, tatlı rüyalar', ru: 'Спокойной ночи, дорогая, сладких снов' },
  { id: 16, sentence: 'Hesabı ben ___', answer: 'öderim', options: ['öderim', 'alırım', 'veririm', 'isterim'], tr_full: 'Hesabı ben öderim', ru: 'Я оплачу счёт' },
  { id: 17, sentence: 'Seni almaya ___', answer: 'geliyorum', options: ['geliyorum', 'gidiyorum', 'kalıyorum', 'bakıyorum'], tr_full: 'Seni almaya geliyorum', ru: 'Еду за тобой' },
  { id: 18, sentence: 'Gel ___, kavga etmeyelim', answer: 'barışalım', options: ['barışalım', 'tartışalım', 'ayrılalım', 'bırakalım'], tr_full: 'Gel barışalım, kavga etmeyelim', ru: 'Давай помиримся, не будем ссориться' },
  { id: 19, sentence: 'Kalbimi ___', answer: 'kırdın', options: ['kırdın', 'aldın', 'verdin', 'tuttun'], tr_full: 'Kalbimi kırdın', ru: 'Ты разбил моё сердце' },
  { id: 20, sentence: 'Bayramınız ___ olsun', answer: 'kutlu', options: ['kutlu', 'güzel', 'hayırlı', 'mutlu'], tr_full: 'Bayramınız kutlu olsun', ru: 'С праздником' },
];
